### ISSUE TITLE
joblib version to prepare "et_score.sav"

### ISSUE THREAD

**Issue by CYP152N1** [miladrayka/ET_Score#2]
I'm going to change from X-SCORE to ET_Score to evaluate the result of docking.
However I cannot use et_score.sav owing to the error shown below.

COMAND

$ /---path to python---/bin/python3.7 predict.py -m et_score.sav -d structures/

ERROR

Traceback (most recent call last):
  File "predict.py", line 59, in <module>
    model = joblib.load(args.model)
  File "/---path to python---/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 585, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/---path to python---/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 504, in _unpickle
    obj = unpickler.load()
  File "/---path to python---/lib/python3.7/pickle.py", line 1088, in load
    dispatch[key[0]](self)
KeyError: 118

I think the error caused by the version of joblib.
can you tell me the joblib version well work?

I introduced joblib by 
$ /---path to python---/lib/python3.7 -m pip install joblib
Collecting joblib
  Using cached joblib-1.0.1-py3-none-any.whl (303 kB)
Installing collected packages: joblib
Successfully installed joblib-1.0.1

Is there any advice for me?
I'm looking to forward to use ET_score.

**Comment by miladrayka** [comment]
My joblib version is 1.0.1 too. I think your problem is related to sklearn version. I think it should be 0.21 or else for loading .sav file.
